Update handy-controls.js
AdaRoseCannon/handy-work pull request #20
Opened 2023-08-22 15:25 UTC by addy1997

changed the getJointPoses() with fillPoses() and fillJointRadii() methods as mentioned in the issue (#18) by @vincentfretin

2023-08-22 16:16 UTC, vincentfretin requested changes
Did you forget to push changes? This is like 20% implemented here. See changes https://github.com/aframevr/aframe/pull/5298/files to have an idea of what need to be changed.

2023-08-22 17:22 UTC, addy1997 commented
Hi @vincentfretin,

Thanks for your reply but I thought that changing the getJointPose() method with suffice because Ada's component uses inputSource API as opposed to the hand-tracking-controls component. 

However, I replaced `controller.hand.values()` with `inputSource.hand.values()`. Do I need to add anything else to the code?

2023-08-23 06:53 UTC, vincentfretin commented
Did you test it? `this.jointPoses` is not defined.

2023-08-23 06:58 UTC, vincentfretin requested changes

2023-08-23 06:58 UTC, vincentfretin commented on src/handy-controls.js
> +            const pose = frame.fillPoses(inputSource.hand.values(), referenceSpace, this.jointPoses) && frame.fillJointRadii(inputSource.hand.values(), this.jointRadii);
`pose` here is now a boolean and not a XRPose. `this.jointPoses` and  this.jointRadii are not defined.

2023-08-23 06:58 UTC, vincentfretin commented on src/handy-controls.js
> +            const pose = frame.fillPoses(inputSource.hand.values(), referenceSpace, this.jointPoses) && frame.fillJointRadii(inputSource.hand.values(), this.jointRadii);
You need to get the pose for each bone from jointPoses and modify https://github.com/AdaRoseCannon/handy-work/blob/6b4a66ca26166091ae1eb5ecf60817786fbdb1b3/src/handy-controls.js#L383-L384

2025-01-04 22:06 UTC, closed without merging